---
application:
  name: "bunnyphp-app"
  project: "test"
  organization: "QoveryCommunity"
  storage:
  - name: "uploads"
    size: "500"
    type: "slow_hdd"
    mount_point: "/mnt/uploads"
databases:
- type: "MYSQL"
  name: "bunny"
  version: "5.7"
- type: "REDIS"
  name: "bunny"
  version: "6"
routers:
- name: "main-bunnyphp-app"
  routes:
  - application_name: "bunnyphp-app"
    paths:
    - "/*"
